def addition(a,b):
    return a+b
def substract(a,b,c):
    return a-b-c
def addition(a,b,c):
    return a+b+c
def substract(a,b):
    return a-b
def devison(a,b):
    return a/b
def product(a,b):
    return a*b
